# Generated by Django 4.2.5 on 2023-10-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_delete_jobskill_alter_jobpost_skill_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='duration',
            field=models.PositiveIntegerField(help_text='duration must be an integer', null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='duration_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH')], max_length=10),
        ),
    ]
