# Generated by Django 4.2.5 on 2023-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobpost_duration_alter_jobpost_duration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='RS', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='currency',
            field=models.CharField(choices=[('RS', 'RUPPEES'), ('USD', 'DOLLAR')], default='RS', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='currency',
            field=models.CharField(choices=[('RS', 'RUPPEES'), ('USD', 'DOLLAR')], default='RS', max_length=3),
            preserve_default=False,
        ),
    ]
