# Generated by Django 4.2.5 on 2023-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_contract_currency_contract_total_jobpost_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='CLOSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobproposal',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('INPROCESS', 'INPROCESS'), ('DENIED', 'DENIED')], default='INPROCESS', max_length=10),
        ),
    ]
