# Generated by Django 4.2.5 on 2023-11-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobpost_status_alter_jobproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remaining',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
