# Generated by Django 4.2.5 on 2023-11-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20231102_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
