# Generated by Django 4.2.5 on 2023-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_review_job_alter_review_review_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='jobproposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10),
        ),
    ]
