# Generated by Django 4.2.5 on 2023-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobpost_options_alter_jobproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.PositiveIntegerField(help_text='job salary'),
        ),
    ]
