# Generated by Django 4.2 on 2023-09-28 06:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_pics/', validators=[accounts.validators.validate_image]),
            preserve_default=False,
        ),
    ]
