# Generated by Django 4.2.5 on 2023-10-05 06:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_client_freelancer_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GD', 'GRADUATION'), ('PG', 'POST GRADUATION')], max_length=2)),
                ('degree_name', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('BEG', 'BEGINEER'), ('INT', 'INTERMIDIATE'), ('EXP', 'EXPERT')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser'},
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Freelancer'},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='Freelancer',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='Education',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='', upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc'], message='only pdf, txt, doc extensions allowed')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc'], message='only pdf , txt , doc extensions allowed')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='years_of_experience',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AddField(
            model_name='education',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.freelancer'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.skill'),
        ),
    ]
