# Generated by Django 4.2.5 on 2023-10-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_bio_alter_selfskills_freelancer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('is_client', 'client user type'),), 'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='freelancer',
            options={'permissions': (('is_freelancer', 'freelancer user type'),), 'verbose_name': 'Freelancer'},
        ),
    ]
