# Generated by Django 4.2.5 on 2023-10-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_gender_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
    ]
