# Generated by Django 4.2.5 on 2023-11-19 16:56

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_customuser_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pics/', validators=[accounts.validators.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg'], message='only jpeg and png extensions allowed')]),
        ),
    ]
